shallow_clone: true

os: Visual Studio 2015

environment:
  matrix:
  - COMPILER: msvc
    GENERATOR: "Visual Studio 14 2015"
    CFLAGS: /MP
    CXXFLAGS: /MP
  - COMPILER: msvc
    GENERATOR: "Visual Studio 14 2015 Win64"
    CFLAGS: /MP
    CXXFLAGS: /MP
  - COMPILER: mingw
    GENERATOR: "MSYS Makefiles"

configuration:
  - Debug
  - Release

init:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - set MSYSTEM=MINGW64

install:
  - mkdir build && cd build
  - >
      cmake
      -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
      %CMAKE_OPTS%
      -G "%GENERATOR%"
      ..

build_script:
  - if %COMPILER% == "mingw" ( cmake --build . -- -j4 ) else ( cmake --build . )

test_script:
  - ctest -j2 --output-on-failure --timeout=10

artifacts:
  path: build
